export const HTTP_BAD_REQUEST_ERROR_CODE = 400;
export const HTTP_UNAUTHORIZED_REQUEST_ERROR_CODE = 401;
export const HTTP_SERVER_ERROR_CODE = 500;
export const HTTP_NOT_FOUND_ERROR_CODE = 404;
export const HTTP_RUNTIME_ERROR_CODE = 400;


export const AUTH_ERROR = 'AUTH_ERROR';
export const AUTH_USER_NOT_FOUND = 'AUTH_USER_NOT_FOUND';
export const UNEXPECTED_ERROR = 'UNEXPECTED_ERROR';
export const RESOURCE_ALREADY_EXISTS_ERROR = 'RESOURCE_ALREADY_EXISTS_ERROR';
export const MAILCHIMP_OAUTH_CODE_ERROR = 'MAILCHIMP_OAUTH_CODE_ERROR';
export const EMAIL_NOT_VERIFIED = 'EMAIL_NOT_VERIFIED';